export const missedFlags = {
  'United Kingdom': 'https://restcountries.eu/data/gbr.svg',
  'Iran, Islamic Republic of': 'https://restcountries.eu/data/irn.svg',
  'Bolivia': 'https://restcountries.eu/data/bol.svg',
  'Moldova': 'https://restcountries.eu/data/mda.svg',
  'Venezuela (Bolivarian Republic)': 'https://restcountries.eu/data/ven.svg',
  'Palestinian Territory': 'https://restcountries.eu/data/pse.svg',
  'Macedonia, Republic of': 'https://restcountries.eu/data/mkd.svg',
  'Korea (South)': 'https://restcountries.eu/data/kor.svg',
  'Congo (Kinshasa)': 'https://restcountries.eu/data/cog.svg',
  'Cape Verde': 'https://restcountries.eu/data/cpv.svg',
  'Syrian Arab Republic (Syria)': 'https://restcountries.eu/data/syr.svg',
  'Congo (Brazzaville)': 'https://restcountries.eu/data/cog.svg',
  'Taiwan, Republic of China': 'https://restcountries.eu/data/twn.svg',
  'Saint Vincent and Grenadines': 'https://restcountries.eu/data/vct.svg',
  'Holy See (Vatican City State)': 'https://restcountries.eu/data/vat.svg',
  'Macao, SAR China': 'https://restcountries.eu/data/mac.svg',
  'Lao PDR': 'https://restcountries.eu/data/lao.svg',
};

export const missedPopulations = {
  'United Kingdom': 65110000,
  'Iran, Islamic Republic of': 79369900,
  'Bolivia': 10985059,
  'Moldova': 3553100,
  'Venezuela (Bolivarian Republic)': 31028700,
  'Palestinian Territory': 4682467,
  'Macedonia, Republic of': 2058539,
  'Korea (South)': 50801405,
  'Congo (Kinshasa)': 4741000,
  'Cape Verde': 531239,
  'Syrian Arab Republic (Syria)': 18564000,
  'Congo (Brazzaville)': 4741000,
  'Taiwan, Republic of China': 23503349,
  'Saint Vincent and Grenadines': 109991,
  'Holy See (Vatican City State)': 451,
  'Macao, SAR China': 649100,
  'Lao PDR': 6492400,
};
